spring:
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
    thymeleaf:
      cache: false
  h2:
    console:
      enabled: true

  datasource:
#    url: jdbc:h2:tcp://localhost/~/startBoot
    url: jdbc:h2:mem:startBoot
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    initialization-mode: always      # schema 자동생성할경우 사용.
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show_sql: true
    hibernate:
#      ddl-auto: none
#      ddl-auto: create
      ddl-auto: create-drop
      properties:
        hibernate:
          format_sql  : true

#logging.level:
#  org.hibernate.SQL: debug
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#server:
#  port: 443

server:
  tomcat:
    basedir: /app/public

mybatis:
  type-aliases-package: com.sinisiro
  mapper-locations: mybatis/mapper/**/*.xml